#!/bin/zsh

rm -r ~/.vim 2> /dev/null
rm ~/.vimrc 2> /dev/null
rm .done 2> /dev/null 

git clone https://github.com/gmarik/Vundle.vim bundle/Vundle.vim

ln -s "$PWD" ~/.vim
ln -s "$PWD/.vimrc" ~/.vimrc
vim +PluginInstall +qall

touch .done
