#!/bin/zsh

rm -r ~/.vim 2> /dev/null
rm ~/.vimrc 2> /dev/null
rm .done 2> /dev/null 

git clone https://github.com/gmarik/vundle.git bundle/vundle

ln -s "$PWD" ~/.vim
ln -s "$PWD/.vimrc" ~/.vimrc
vim +BundleInstall +qall

touch .done
